export const eBooks = [
    {
        title: "The Midnight Library",
        author: "Matt Haig",
        genre: "Fantasy",
        publicationDate: "2020-08-13",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/81J6APjwxlL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A magical and thought-provoking novel about a library between life and death."
    },
    {
        title: "Where the Crawdads Sing",
        author: "Delia Owens",
        genre: "Fiction",
        publicationDate: "2018-08-14",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/810RZxeCZXL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A heart-wrenching and atmospheric novel about a young girl growing up in the marshes of North Carolina."
    },
    {
        title: "Educated",
        author: "Tara Westover",
        genre: "Non-Fiction",
        publicationDate: "2018-02-20",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/71QIkI8YetL._AC_UF1000,1000_QL80_.jpg",
        status: "New Release",
        description: "A memoir about a woman who was born into a survivalist family and went on to earn a Ph.D. from Cambridge University."
    },
    {
        title: "Becoming",
        author: "Michelle Obama",
        genre: "Non-Fiction",
        publicationDate: "2018-11-13",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/81+QX4VMrmS._AC_UF1000,1000_QL80_.jpg",
        status: "New Release",
        description: "A memoir about the life of Michelle Obama, former First Lady of the United States."
    },
    {
        title: "The Vanishing Half",
        author: "Brit Bennett",
        genre: "Fiction",
        publicationDate: "2020-06-02",
        borrow: true,
        return: false,
        image: "https://static.bookofthemonth.com/covers/list/TheVanishingHalf_BOTY2020_200x300.jpg",
        status: "popular",
        description: "A novel about twin sisters who grow up to live very different lives, one passing as white and the other embracing her black heritage."
    },
    {
        title: "The Invisible Life of Addie LaRue",
        author: "V.E. Schwab",
        genre: "Fantasy",
        publicationDate: "2020-10-06",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/71xtFihyn-L._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A fantasy novel about a young woman who makes a deal with the devil to live forever, but is cursed to be forgotten by everyone she meets."
    },
    {
        title: "People We Meet on Vacation",
        author: "Emily Henry",
        genre: "Romance",
        publicationDate: "2021-05-11",
        borrow: true,
        return: false,
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1618913179l/54985743.jpg",
        status: "New Release",
        description: "A romantic novel about two friends who take a trip together and discover their feelings for each other."
    },
    {
        title: "It Ends with Us",
        author: "Colleen Hoover",
        genre: "Romance",
        publicationDate: "2016-08-02",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/813aV273-rL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A romantic novel about a woman who falls in love with a man, but struggles with her past and her feelings for him."
    },
    {
        title: "The Hating Game",
        author: "Sally Thorne",
        genre: "Romance",
        publicationDate: "2016-08-09",
        borrow: true,
        return : false,
        image: "https://m.media-amazon.com/images/I/817HkQzwK8L._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A romantic novel about two co-workers who engage in a series of pranks and one-upmanship until they realize their feelings for each other."
    },
    {
        title: "Red, White & Royal Blue",
        author: "Casey McQuiston",
        genre: "Romance",
        publicationDate: "2019-05-14",
        borrow: true,
        return: false,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566742512i/41150487.jpg",
        status: "popular",
        description: "A romantic novel about the First Son of the United States who falls in love with the Prince of Wales."
    },
    {
        title: "The Kiss Quotient",
        author: "Helen Hoang",
        genre: "Romance",
        publicationDate: "2018-05-30",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/81mKbEH0G2L._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A romantic novel about a woman with Asperger's who sets out to improve her dating life by hiring an escort."
    },
    {
        title: "Beach Read",
        author: "Emily Henry",
        genre: "Romance",
        publicationDate: "2020-05-19",
        borrow: true,
        return: false,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1589881197i/52867387.jpg",
        status: "Trending",
        description: "A romantic novel about two writers who find love in a small beach town."
    },
    {
        title: "The Unhoneymooners",
        author: "Christina Lauren",
        genre: "Romance",
        publicationDate: "2019-05-14",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/71PVJVuMMQL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A romantic novel about two sworn enemies who are forced to pretend to be newlyweds on a honeymoon."
    },
    {
        title: "Malibu Rising",
        author: "Taylor Jenkins Reid",
        genre: "Fiction",
        publicationDate: "2021-06-01",
        borrow: true,
        return: false,
        image: "https://cdn.kobo.com/book-images/7fdaae96-91e7-4c9c-a534-6eb3e725c683/1200/1200/False/malibu-rising.jpg",
        status: "Recently Released",
        description: "A novel about four siblings who throw an epic party in Malibu in the 1980s."
    },
    {
        title: "The Seven Husbands of Evelyn Hugo",
        author: "Taylor Jenkins Reid",
        genre: "Fiction",
        publicationDate: "2017-06-13",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/71KcUgYanhL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A novel about a reclusive Hollywood star who recounts her life story and her seven marriages."
    },
    {
        title: "Anxious People",
        author: "Fredrik Backman",
        genre: "Fiction",
        publicationDate: "2020-09-08",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/810XLL7gvRL._AC_UF1000,1000_QL80_.jpg",
        status: "Recently Released",
        description: "A novel about a group of strangers who are brought together during a failed bank robbery."
    },
    {
        title: "Circe",
        author: "Madeline Miller",
        genre: "Fantasy",
        publicationDate: "2018-04-10",
        borrow: true,
        return: false,
        image: "https://i.pinimg.com/736x/3b/62/0c/3b620c5ed0688d4c25d606920b51aed1.jpg",
        status: "Trending",
        description: "A fantasy novel that reimag ines the witch Circe from Homer's Odyssey."
    },
    {
        title: "The Song of Achilles",
        author: "Madeline Miller",
        genre: "Fantasy",
        publicationDate: "2012-09-20",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/81msb6gUBTL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A fantasy novel that reimagines the Trojan War from the perspective of Achilles' lover Patroclus."
    },
    {
        title: "A Court of Thorns and Roses",
        author: "Sarah J. Maas",
        genre: "Fantasy",
        publicationDate: "2015-05-05",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/81RrEEMiOCL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A fantasy novel about a human girl who is taken captive by a faerie lord."
    },
    {
        title: "Normal People",
        author: "Sally Rooney",
        genre: "Romance",
        publicationDate: "2018-08-28",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/M/MV5BYWUzNjQ2YmYtNWI3Yi00NzNmLWJjYWYtMDFiM2RjYjNjZWZmXkEyXkFqcGc@._V1_.jpg",
        status: "Trending",
        description: "A romantic novel about two young people who navigate a complex and intense relationship."
    },
    {
        title: "The Flatshare",
        author: "Beth O'Leary",
        genre: "Romance",
        publicationDate: "2019-04-18",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/71cschSkfIL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A romantic novel about two people who share a flat, but have never met until they fall in love."
    },
    {
        title: "One Day in December",
        author: "Josie Silver",
        genre: "Romance",
        publicationDate: "2018-12-12",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/819WqcidSnL._AC_UF1000,1000_QL80_.jpg",
        status: "popular",
        description: "A romantic novel about a woman who falls in love with a man she sees on a bus, but doesn't meet until a year later."
    },
    {
        title: "The Wedding Date",
        author: "Jasmine Guillory",
        genre: "Romance",
        publicationDate: "2018-01-30",
        borrow: true,
        return: false,
        image: "https://assets.lastdodo.com/image/ld_large/plain/assets/catalog/assets/2020/7/14/b/4/1/pdf_b4180570-c60b-11ea-9ffd-85cc9669d67d.jpg",
        status: "Trending",
        description: "A romantic novel about a woman who hires a fake boyfriend to accompany her to a wedding."
    },
    {
        title: "The Rosie Project",
        author: "Graeme Simsion",
        genre: "Romance",
        publicationDate: "2013-04-01",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/412k1wR-tTL._AC_UF1000,1000_QL80_.jpg",
        status: "popular",
        description: "A romantic novel about a socially awkward professor who sets out to find the perfect partner using a scientific approach."
    },
    {
        title: "The Light We Lost",
        author: "Jill Santopolo",
        genre: "Romance",
        publicationDate: "2017-05-09",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/71Fims5zxsL._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A romantic novel about two friends who fall in love, but are separated by distance and circumstance."
    },
    {
        title: "Heartstopper: Volume One",
 author: "Alice Oseman",
        genre: "Graphic Novel",
        publicationDate: "2019-02-01",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/91CQEcpbkCL._AC_UF1000,1000_QL80_.jpg",
        status: "popular",
        description: "A graphic novel about two teenage boys who fall in love in a British high school."
    },
    {
        title: "Daisy Jones & The Six",
        author: "Taylor Jenkins Reid",
        genre: "Fiction",
        publicationDate: "2019-03-05",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/818B6S6B-bL._AC_UF1000,1000_QL80_.jpg",
        status: "popular",
        description: "A novel about a fictional rock band in the 1970s and their rise to fame."
    },
    {
        title: "The Book Thief",
        author: "Markus Zusak",
        genre: "Historical Fiction",
        publicationDate: "2005-03-14",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/91JGwQlnu7L._AC_UF1000,1000_QL80_.jpg",
        status: "Trending",
        description: "A historical novel about a young girl living in Nazi Germany during World War II."
    },
    {
        title: "The Great Alone",
        author: "Kristin Hannah",
        genre: "Fiction",
        publicationDate: "2018-02-06",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/91lFMYj1XtL._AC_UF1000,1000_QL80_.jpg",
        status: "popular",
        description: "A novel about a young couple who move to Alaska and must confront the harsh realities of living off the grid."
    },
    {
        title: "The Silent Patient",
        author: "Alex Michaelides",
        genre: "Thriller",
        publicationDate: "2019-02-05",
        borrow: true,
        return: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRZKRYwK-lWX0_AKS3jH4b4HYblz0bIm3RUg&s",
        status: "Trending",
        description: "A thriller novel about a famous painter who is accused of murdering her husband and refuses to speak or cooperate with the police."
    },
    {
        title: "Big Little Lies",
        author: "Liane Moriarty",
        genre: "Fiction",
        publicationDate: "2014-07-29",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/M/MV5BY2E3ODNhNWYtYWQ0ZS00ZjdlLTg5NjItMzYwMTlkN2I3YTFjXkEyXkFqcGc@._V1_.jpg",
        status: "Trending",
        description: "A novel about three mothers whose lives become intertwined in a small coastal town."
    },
    {
        title: "A Man Called Ove",
        author: "Fredrik Backman",
        genre: "Fiction",
        publicationDate: "2012-04-02",
        borrow: true,
        return: false,
        image: "https://m.media-amazon.com/images/I/81g2oEdeGTL._AC_UF1000,1000_QL80_.jpg",
        status: "popular",
        description: "A novel about a grumpy old man who forms an unlikely friendship with his neighbors."
    }
];